name: Validate GitHub Actions Workflows
permissions: {}

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'

jobs:

  validate:
    uses: project-ncl/shared-github-actions/.github/workflows/validate-gh-action.yml@504efc82df7d4f73e3bd2b67bec31bcd532ed9e4 # v0.0.14
